### PR TITLE
[BUGFIX] Lowercase filename for case sensitive systems

### PR DESCRIPTION
**Pull request by IchHabRecht**

### CODE REVIEW

**Comment by etobi** [comment]
We're struggling with exactly this file for a while now.

For the autoload look fine without your commit. See https://github.com/TYPO3-Caretaker/caretaker/tree/master/classes/helpers/tt_address
Could you please double check?

Thanks in advance
   tobias

**Comment by IchHabRecht** [comment]
Okay, we have the current official 0.7.3 on our server where this problem occurred. Seems you have moved that file in master (https://github.com/TYPO3-Caretaker/caretaker/commit/df9f743c3f4f53fde6ac8d53ef59626d935f17d5) now (was https://github.com/TYPO3-Caretaker/caretaker/tree/0.7.3/classes/helpers/tt_address)

**Comment by IchHabRecht** [comment]
Would have been good to release an update with this (important) fix btw ^^

**Comment by etobi** [comment]
yes, you're right.
It was part of some compatibility fixes for 7.5.x and I'm going to release a new version like tomorrow.

**Pull request closed without merging**
